### ISSUE TITLE
Executing jobs on Jenkins Slaves

### ISSUE THREAD

**Issue by smitcham** [palantir/stashbot#12]
My jenkins environment uses multiple slaves to partition builds from different groups and different build environments.  I've just started digging through the configuration options, but is there a way to configure a particular slave for a publish and/or verify build?

**Comment by terabyte** [comment]
Yeah, good question.  So this is what "labels" are for - you can give certain repositories "labels" and then give those labels to your jenkins nodes to specify which nodes get which jobs.  You can't separate publish from verify jobs at this time though, without using the "custom job settings" functionality (which means manually editing the jobs after stashbot makes them and asking stashbot not to overwrite the changes).

**Comment by smitcham** [comment]
The labels worked correctly.
