### ISSUE TITLE
Triggering jobs on jenkins

### ISSUE THREAD

**Issue by alex131290** [palantir/stashbot#22]
How can i trigger jobs on jenkins upon each push that has been made to the repository?

**Comment by terabyte** [comment]
@alex131290 stashbot is designed to be a specific solution for continuous integration - it can't trigger any arbitrary job, only the jobs it creates to do CI.  So if I understand what you are asking, the answer is "that is a feature not yet supported".

If you want to use stashbot to have a certain script run, or a set of tests run, on every push to the repository, you can set that script as the verify command, and set a verify regular expression that matches all branches.  Then, a job is created in jenkins and every push to the repository will trigger it.

Does that answer your question?

**Comment by terabyte** [comment]
This should probably be closed, if there aren't any more questions.
