### ISSUE TITLE
actively harmful to current stash releases

### ISSUE THREAD

**Issue by memory** [palantir/stashbot#27]
Presently, the released version of stashbot not only will not run on current (3.11.3) versions of stash, but actively breaks the system: if installed (either manually or via the marketplace) the OPM "installing" dialogue hangs midway through, and if the user is unwise enough to restart the stash server, stash itself fails with a SpringMVC error.  The following is seen in the logs:

```
2015-09-22 14:08:47,102 ERROR [ThreadPoolAsyncTaskExecutor::Thread 38] stash_admin @13SGSAEx848x435x0 1xdwnw6 50.59.189.124,127.0.0.1 "POST /rest/plugins/1.0/ HTTP/1.0" c.a.plugin.osgi.factory.OsgiPlugin Unable to start the plugin container for plugin 'com.palantir.stash.stashbot'
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.palantir.stash.stashbot.outputhandler.CommandOutputHandlerFactory] for bean with name 'commandOutputHandlerFactory' defined in URL [bundle://104.0:0/META-INF/spring/atlassian-plugins-components.xml]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: com/palantir/stash/stashbot/outputhandler/CommandOutputHandlerFactory : Unsupported major.minor version 52.0
```

**Comment by terabyte** [comment]
If you read the nested exception, I suspect you will see that this is not caused by incompatibility with the current stash version, it is caused by running stash with < JDK8 (which atlassian themselves no longer support).

The stashbot plugin jar is built using JDK8 and it requires it.  Remove the stash jar from your $STASH_HOME under the plugins directory and it will "Fix" things.

**Comment by memory** [comment]
Ah, sadly you appear to be correct.  I say sadly because I was using the
official Atlassian AWS distribution (cloudformation+AMI), which apparently
still uses java 7.  (Probably because the amazon linux AMI still defaults
to it.)

On Mon, Sep 28, 2015 at 10:16 AM, Carl Myers <notifications@github.com>
wrote:

> If you read the nested exception, I suspect you will see that this is not
> caused by incompatibility with the current stash version, it is caused by
> running stash with < JDK8 (which atlassian themselves no longer support).
>
> The stashbot plugin jar is built using JDK8 and it requires it. Remove the
> stash jar from your $STASH_HOME under the plugins directory and it will
> "Fix" things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/palantir/stashbot/issues/27#issuecomment-143808586>.
>



-- 
Everyone knows history moves in circles;
the surprise is how big the circles are.
  (--Greil Marcus)

**Comment by terabyte** [comment]
@memory - ah, that is useful to know!  FWIW, there is nothing JDK8 specific in stashbot, and you should be able to build a compatible version by cloning the repo, running "./bin/invoke-sdk.sh clean test package", and then uploading the plugin jar in the target/ directory.

**Comment by memory** [comment]
Does the add-on store offer any means to filter based on jvm version?  There are probably many people still running on j7 out there, and it's definitely a bad experience that you can click "install" on what appears to be something atlassian blessed installing, and suddenly you no longer have a stash server. :(

(I eventually figured out all the places I needed to delete the jar on-disk to make the problem go away, but it was not a fun thing to do.)

**Comment by terabyte** [comment]
@memory - for shizzle - this seems like a pretty big failing of the Universal Plugin Manager itself that it will allow you to try to install a jar that its own JDK can't read, and won't give you an error message at all.  The easiest fix is to block installation with a sane error message.  The best experience for the user would be to do that *and* add a way to filter marketplace jars as well.  @bturner - any idea of Atlassian is aware of this issue?  We could also search their public jira instance I guess.

**Comment by terabyte** [comment]
just to come back and update this issue - it looks like atlassian "solved" this problem by requiring jdk8 for bitbucket 4.+.  This means everything will have to be running jdk8 and building for jdk8 in order for it to be bitbucket compatible.
